import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { COLORS } from '../constants/colours';
import { useLang } from '../context/LangContext';

export default function DigestCard({ digest, score, week, scoreDelta }) {
  const { lang } = useLang();
  const deltaSign = scoreDelta >= 0 ? '+' : '';
  const deltaColour = scoreDelta >= 0 ? COLORS.success : COLORS.danger;

  return (
    <View style={styles.card}>
      {/* Header row */}
      <View style={styles.header}>
        <View>
          <Text style={styles.weekLabel}>{week || (lang === 'en' ? 'This Week' : 'Minggu Ini')}</Text>
          <Text style={styles.digestTitle}>{lang === 'en' ? 'Weekly AI Summary' : 'Ringkasan Mingguan AI'}</Text>
        </View>
        <View style={styles.scoreBadge}>
          <Text style={styles.scoreValue}>{score}</Text>
          <Text style={styles.scoreMax}>/100</Text>
          {scoreDelta !== undefined && (
            <View style={[styles.deltaBadge, { backgroundColor: deltaColour + '20' }]}>
              <Text style={[styles.deltaText, { color: deltaColour }]}>
                {deltaSign}{scoreDelta}
              </Text>
            </View>
          )}
        </View>
      </View>

      {/* Divider */}
      <View style={styles.divider} />

      {/* Digest text */}
      <View style={styles.digestBody}>
        <Text style={styles.quoteIcon}>"</Text>
        <Text style={styles.digestText}>{digest || (lang === 'en' ? 'No summary available.' : 'Tiada ringkasan tersedia.')}</Text>
        <Text style={styles.quoteIconClose}>"</Text>
      </View>

      {/* Footer label */}
      <View style={styles.footer}>
        <View style={styles.aiLabel}>
          <Text style={styles.aiLabelText}>{lang === 'en' ? '✨ Generated by Claude AI' : '✨ Dijana oleh Claude AI'}</Text>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    padding: 20,
    marginHorizontal: 16,
    marginVertical: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  weekLabel: {
    fontSize: 11,
    color: COLORS.textSecondary,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 3,
  },
  digestTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  scoreBadge: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 2,
  },
  scoreValue: {
    fontSize: 28,
    fontWeight: '900',
    color: COLORS.primary,
  },
  scoreMax: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginTop: 8,
  },
  deltaBadge: {
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 6,
    marginTop: 6,
  },
  deltaText: {
    fontSize: 12,
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginBottom: 14,
  },
  digestBody: {
    marginBottom: 14,
  },
  quoteIcon: {
    fontSize: 32,
    color: COLORS.primary,
    lineHeight: 28,
    marginBottom: 4,
    fontWeight: '900',
  },
  digestText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    lineHeight: 22,
    fontStyle: 'italic',
  },
  quoteIconClose: {
    fontSize: 32,
    color: COLORS.primary,
    lineHeight: 28,
    textAlign: 'right',
    fontWeight: '900',
  },
  footer: {
    alignItems: 'flex-end',
  },
  aiLabel: {
    backgroundColor: COLORS.primary + '20',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  aiLabelText: {
    fontSize: 11,
    color: COLORS.primary,
    fontWeight: '600',
  },
});
